### ISSUE TITLE
Fix link rewriter in "distribution"

### ISSUE THREAD

**Issue by lukasbarinka** [internetguru/academy#24]
Links in README.md are rewrited with wrong address.

e.g.: https://gitlab.wr.cz/fit/bi-skj/main/shell-intro/bi-skj-shell-intro-lukasbarinka

Original URL: 
`https://gitlab.wr.cz/fit/bi-skj/shell-intro/-/raw/main/courses/index.html`

Rewrited URL:
`https://gitlab.wr.cz/fit/bi-skj/main/`**`shell-intro/`**`bi-skj-shell-intro-lukasbarinka/-/raw/main/courses/index.html`

**Comment by jiripavelka** [comment]
Elaborate please
