### ISSUE TITLE
Normalize "collect" job

### ISSUE THREAD

**Issue by lukasbarinka** [internetguru/academy#26]
The "collect" job differs from other jobs in several aspects. It uses different artifacts directory (`.collect` instead of `.results`) and it mixes academy script execution with residual scripts in CI/CD job.

- [ ] use `.results` directory as an artifact path
- [ ] move the script generating `summary.txt` into `academy` script, using:  
       `exec > >( tee .results/summary.txt )`
- [ ] remove the command `mv 'summary.txt' '.collect/'`
- [ ] consider re/moving final echoes (into `academy` script as well if necessary)

**Comment by jiripavelka** [comment]
The 'collect' job is being redesigned, see issue #33 and feel free to comment and contribute.
