### ISSUE TITLE
Check protected branch

### ISSUE THREAD

**Issue by petrzpav** [internetguru/academy#49]
Check current branch is protected in CI global init. Consider set  protected branch automatically in Dashboard.

**Comment by jiripavelka** [comment]
- Let's discuss/design this.
- Assuming this is analogous and subordinate to the include verification issue at https://github.com/internetguru/dashboard/issues/69

**Comment by jiripavelka** [comment]
tl:dr
Check for required variables, such as academy_token and academy_db and report missing with possible causes: undefined, invalid scope, or unprotected branch.

**Comment by petrzpav** [comment]
There was already some checks, so I verified them and I only added check to missing/empty academy_db
