### ISSUE TITLE
Unreliable display of badges

### ISSUE THREAD

**Issue by jiripavelka** [internetguru/academy#56]
Badges on the dashboard are not displayed reliably. Even if the correct badge is in the artifacts, the wrong badge is displayed on the dashboard. Neither refresh, reload nor evaluate helps.

![Image](https://github.com/internetguru/academy/assets/77435991/ff43b34e-9ce3-42fe-8691-bf930593eb3e)

In the artifacts there is an SVG that has passed Tests 7/7, but on the dashboard 0/7.

https://gl.iga.ksi.fit.cvut.cz/bi-uos/b231/names/zapotjos/-/jobs/289468/artifacts/raw/.results/badge-evaluate-tests.svg?inline=false

**Comment by jiripavelka** [comment]
The problem is caused by the group token, which unfortunately cannot create tokens. As a hotfix, we introduced a specific error message.

To support recovery, we ensured that the token is created with each distribution as another hotfix. We also updated the documentation (on staging) to explain why group tokens should not be used and to consider creating an extra user with limited scope for shared repositories.

To recover, simply create a personal access token and run distribute again.

**Comment by lukasbarinka** [comment]
- I have created a BI-UOS bot user who is a group/course maintainer.
- I used his token in CI.
- Following your advice, I called distribute (although I don't understand why).
- Submit job is still failing, this time with the message: `Missing ACADEMY_SUBMIT_TOKEN variable or token`.

Can you please throw here a link to the documentation where you describe this? I didn't find it on github (the last documentation edit on staging is 3 months old). BTW, overall I either don't understand the documentation or it's pretty poor - basically just a skeleton.

**Comment by jiripavelka** [comment]
-- Our test passed as follows:
^ Manual pipeline on main branch (#61191) passed.
^ Automatically triggered submit branch evaluate and meta (#61192) passed.

-- User zapotjos Pipeline list
https://gl.iga.ksi.fit.cvut.cz/bi-uos/b231/names/zapotjos/-/pipelines

-- README / GitLab CI Variables / ACADEMY_GITLAB_ACCESS_TOKEN (5 days old)
https://github.com/internetguru/academy/blob/staging/README.md#gitlab-ci-variables

Note: To clear up your confusion, running a distribution job was necessary to fix the submission job, which involved creating the missing (internal) variable...

**Comment by lukasbarinka** [comment]
The described problem still persists. Generated badges are up-to-date and displayed correctly (for each task) when called explicitly.  Your badges (implicitly displayed at the beginning of the page) are wrong (from the cache?).

See image and task status 0/2 (bad) at the top, 2/2 (good) at the task.

Address: https://iga.ksi.fit.cvut.cz/bi-skj/b232/shell-intro/barinkl?group=b232

![Image](https://github.com/internetguru/academy/assets/77435991/ef43db5a-b850-406e-a194-6fa0bfcd044a)

**Comment by jiripavelka** [comment]
Our findings show the displayed badges on the Dashboard correctly reflect badges on the submit branch as intended. The key factor is the evaluation difference between the main branch and the submit branch. By design this can appear in a consequence of edit restrictions defined in the editable file.

**Comment by lukasbarinka** [comment]
OK. In that case, there is a problem with the handling of the ACADEMY_EDITABLE variable, which no longer supports extglob (extended globbing). It would be nice to support it again (`shopt -s extglob`), see https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html . It would also be nice to support `**` (`shopt -s globstar`) to match the documentation in the README (I haven't tested it). 

In that case, I recommend using a reference to the bash (authoritative) documentation in the README instead of ABS.
